[package]
name = "beech-core"
version = "0.1.0"
edition = "2024"

[dependencies]
beech-disk = { path = "../beech-disk" }
thiserror.workspace = true
arrow-array = "=59.3.0"
arrow-schema = "=59.3.0"
arrow-select = "=59.3.0"
parquet = { version = "=59.3.0", default-features = false, features = ["arrow", "snap"] }
bytes = "1.10"
thrift = { version = "=0.24.0", default-features = false }
sha2 = "0.10.9"

[dev-dependencies]
beech-shaper = { path = "../beech-shaper" }
