[package]
name = "beech-disk"
version = "0.1.0"
edition = "2024"

[dependencies]
beech-mem = { path = "../beech-mem" }
tempfile = "3"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Storage_FileSystem"] }

[target.'cfg(target_os = "macos")'.dependencies]
libc = "0.2"
